### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Senor-Ducky** [youdidNGO/youdidNGO.github.io#7]
Your website won't load on github pages if you keep all the html, stylesheet files inside another folder, it must be present at the root of the directory

**Comment by BullsEye34** [comment]
Hi Rahul Mishra.
Thank you for contacting us.

This is to inform you that we are very much aware of GitHub Pages, and
we're not having any issues.

Thank you for writing to us.
Have a great day/night ahead.

Cheers,
WebMaster, YOUDID NGO.
